import type { BookCatalog } from "@/lib/books/types";

/** Fallback catalog when crawl has not run yet. */
export const seedCatalog: BookCatalog = {
  updatedAt: "2026-07-26T00:00:00.000Z",
  updatedAtKst: "2026. 7. 26. 오전 9:00",
  bookNews: [
    {
      id: "seed-news-1",
      title: "신간·서평 뉴스는 매일 오전 9시(한국시간)에 갱신됩니다",
      excerpt:
        "한겨레 책 섹션, 조선일보 책, Google 뉴스(서평·신간)에서 공개 페이지를 수집합니다.",
      link: "https://www.hani.co.kr/arti/culture/book/",
      source: "SavvyBookClub",
      sourceKey: "seed",
    },
    {
      id: "seed-news-2",
      title: "한겨레 ‘책과 생각’에서 최근 도서 논평을 확인하세요",
      excerpt: "크롤 동기화 전이라면 이 미리보기 링크를 눌러 원문을 볼 수 있습니다.",
      link: "https://www.hani.co.kr/arti/culture/book/",
      source: "한겨레",
      sourceKey: "seed",
    },
  ],
  sections: {
    domesticBestsellers: [
      {
        id: "seed-ko-1",
        title: "작별하지 않는다",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/27692/87/cover500/8936434128_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=276928761",
        source: "seed",
        language: "ko",
        rank: 1,
        publisher: "문학동네",
      },
      {
        id: "seed-ko-2",
        title: "채식주의자",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/541/21/cover500/8936433598_2.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=541215",
        source: "seed",
        language: "ko",
        rank: 2,
        publisher: "창비",
      },
      {
        id: "seed-ko-3",
        title: "달러구트 꿈 백화점",
        author: "이미예",
        coverUrl: "https://image.aladin.co.kr/product/24512/70/cover500/k392630952_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=245127091",
        source: "seed",
        language: "ko",
        rank: 3,
        publisher: "팩토리나인",
      },
      {
        id: "seed-ko-4",
        title: "아몬드",
        author: "손원평",
        coverUrl: "https://image.aladin.co.kr/product/13796/13/cover500/8936434268_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=137961340",
        source: "seed",
        language: "ko",
        rank: 4,
        publisher: "창비",
      },
      {
        id: "seed-ko-5",
        title: "미드나잇 라이브러리",
        author: "매트 헤이그",
        coverUrl: "https://image.aladin.co.kr/product/24507/69/cover500/k582630839_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=245076942",
        source: "seed",
        language: "ko",
        rank: 5,
        publisher: "인플루엔셜",
      },
      {
        id: "seed-ko-6",
        title: "불편한 편의점",
        author: "김호연",
        coverUrl: "https://image.aladin.co.kr/product/27614/28/cover500/k392834515_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=276142801",
        source: "seed",
        language: "ko",
        rank: 6,
        publisher: "나무옆의자",
      },
    ],
    newReleases: [
      {
        id: "seed-new-1",
        title: "작별하지 않는다",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/27692/87/cover500/8936434128_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 1,
        publisher: "문학동네",
      },
      {
        id: "seed-new-2",
        title: "채식주의자",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/541/21/cover500/8936433598_2.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 2,
        publisher: "창비",
      },
      {
        id: "seed-new-3",
        title: "아몬드",
        author: "손원평",
        coverUrl: "https://image.aladin.co.kr/product/13796/13/cover500/8936434268_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 3,
        publisher: "창비",
      },
      {
        id: "seed-new-4",
        title: "달러구트 꿈 백화점",
        author: "이미예",
        coverUrl: "https://image.aladin.co.kr/product/24512/70/cover500/k392630952_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 4,
        publisher: "팩토리나인",
      },
    ],
    foreignBestsellers: [
      {
        id: "seed-foreign-1",
        title: "Atomic Habits",
        author: "James Clear",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "en",
        rank: 1,
        publisher: "Avery",
      },
      {
        id: "seed-foreign-2",
        title: "The Midnight Library",
        author: "Matt Haig",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "en",
        rank: 2,
        publisher: "Viking",
      },
      {
        id: "seed-foreign-3",
        title: "Project Hail Mary",
        author: "Andy Weir",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "en",
        rank: 3,
        publisher: "Ballantine",
      },
      {
        id: "seed-foreign-4",
        title: "Educated",
        author: "Tara Westover",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "en",
        rank: 4,
        publisher: "Random House",
      },
    ],
    yes24Bestsellers: [
      {
        id: "seed-yes-1",
        title: "역행자",
        author: "자청",
        coverUrl: "https://image.yes24.com/goods/109707125/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 1,
      },
      {
        id: "seed-yes-2",
        title: "세이노의 가르침",
        author: "세이노",
        coverUrl: "https://image.yes24.com/goods/117014146/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 2,
      },
      {
        id: "seed-yes-3",
        title: "원씽",
        author: "게리 켈러",
        coverUrl: "https://image.yes24.com/goods/74719531/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 3,
      },
      {
        id: "seed-yes-4",
        title: "데일 카네기 인간관계론",
        author: "데일 카네기",
        coverUrl: "https://image.yes24.com/goods/15855097/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 4,
      },
    ],
    englishBestsellers: [
      {
        id: "seed-nyt-1",
        title: "The Women",
        author: "Kristin Hannah",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781250178633-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 1,
        publisher: "St. Martin's Press",
      },
      {
        id: "seed-nyt-2",
        title: "Iron Flame",
        author: "Rebecca Yarros",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781649374172-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 2,
        publisher: "Red Tower Books",
      },
      {
        id: "seed-nyt-3",
        title: "Funny Story",
        author: "Emily Henry",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780593441282-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 3,
        publisher: "Berkley",
      },
      {
        id: "seed-nyt-4",
        title: "James",
        author: "Percival Everett",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780385550369-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 4,
        publisher: "Doubleday",
      },
      {
        id: "seed-nyt-5",
        title: "The Heaven & Earth Grocery Store",
        author: "James McBride",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780593422946-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 5,
        publisher: "Riverhead",
      },
      {
        id: "seed-nyt-6",
        title: "Fourth Wing",
        author: "Rebecca Yarros",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9781649374042-L.jpg",
        link: "https://openlibrary.org/trending/daily",
        source: "seed",
        language: "en",
        rank: 6,
        publisher: "Red Tower Books",
      },
    ],
  },
};
