import type { BookCatalog } from "@/lib/books/types";

/** Fallback catalog when crawl has not run yet. */
export const seedCatalog: BookCatalog = {
  updatedAt: "2026-07-26T00:00:00.000Z",
  updatedAtKst: "2026. 7. 26. 오전 9:00",
  bookNews: [
    {
      id: "seed-news-1",
      title: "신간·서평 뉴스는 매일 오전 9시(한국시간)에 갱신됩니다",
      excerpt:
        "한겨레 책 섹션, 조선일보 책, Google 뉴스(서평·신간)에서 공개 페이지를 수집합니다.",
      link: "https://www.hani.co.kr/arti/culture/book/",
      source: "SavvyBookClub",
      sourceKey: "seed",
    },
    {
      id: "seed-news-2",
      title: "한겨레 ‘책과 생각’에서 최근 도서 논평을 확인하세요",
      excerpt: "크롤 동기화 전이라면 이 미리보기 링크를 눌러 원문을 볼 수 있습니다.",
      link: "https://www.hani.co.kr/arti/culture/book/",
      source: "한겨레",
      sourceKey: "seed",
    },
  ],
  sections: {
    domesticBestsellers: [
      {
        id: "seed-ko-1",
        title: "작별하지 않는다",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/27692/87/cover500/8936434128_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=276928761",
        source: "seed",
        language: "ko",
        rank: 1,
        publisher: "문학동네",
      },
      {
        id: "seed-ko-2",
        title: "채식주의자",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/541/21/cover500/8936433598_2.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=541215",
        source: "seed",
        language: "ko",
        rank: 2,
        publisher: "창비",
      },
      {
        id: "seed-ko-3",
        title: "달러구트 꿈 백화점",
        author: "이미예",
        coverUrl: "https://image.aladin.co.kr/product/24512/70/cover500/k392630952_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=245127091",
        source: "seed",
        language: "ko",
        rank: 3,
        publisher: "팩토리나인",
      },
      {
        id: "seed-ko-4",
        title: "아몬드",
        author: "손원평",
        coverUrl: "https://image.aladin.co.kr/product/13796/13/cover500/8936434268_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=137961340",
        source: "seed",
        language: "ko",
        rank: 4,
        publisher: "창비",
      },
      {
        id: "seed-ko-5",
        title: "미드나잇 라이브러리",
        author: "매트 헤이그",
        coverUrl: "https://image.aladin.co.kr/product/24507/69/cover500/k582630839_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=245076942",
        source: "seed",
        language: "ko",
        rank: 5,
        publisher: "인플루엔셜",
      },
      {
        id: "seed-ko-6",
        title: "불편한 편의점",
        author: "김호연",
        coverUrl: "https://image.aladin.co.kr/product/27614/28/cover500/k392834515_1.jpg",
        link: "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=276142801",
        source: "seed",
        language: "ko",
        rank: 6,
        publisher: "나무옆의자",
      },
    ],
    newReleases: [
      {
        id: "seed-new-1",
        title: "작별하지 않는다",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/27692/87/cover500/8936434128_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 1,
        publisher: "문학동네",
      },
      {
        id: "seed-new-2",
        title: "채식주의자",
        author: "한강",
        coverUrl: "https://image.aladin.co.kr/product/541/21/cover500/8936433598_2.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 2,
        publisher: "창비",
      },
      {
        id: "seed-new-3",
        title: "아몬드",
        author: "손원평",
        coverUrl: "https://image.aladin.co.kr/product/13796/13/cover500/8936434268_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 3,
        publisher: "창비",
      },
      {
        id: "seed-new-4",
        title: "달러구트 꿈 백화점",
        author: "이미예",
        coverUrl: "https://image.aladin.co.kr/product/24512/70/cover500/k392630952_1.jpg",
        link: "https://www.aladin.co.kr/",
        source: "seed",
        language: "ko",
        rank: 4,
        publisher: "팩토리나인",
      },
    ],
    foreignBestsellers: [],
    yes24Bestsellers: [
      {
        id: "seed-yes-1",
        title: "역행자",
        author: "자청",
        coverUrl: "https://image.yes24.com/goods/109707125/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 1,
      },
      {
        id: "seed-yes-2",
        title: "세이노의 가르침",
        author: "세이노",
        coverUrl: "https://image.yes24.com/goods/117014146/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 2,
      },
      {
        id: "seed-yes-3",
        title: "원씽",
        author: "게리 켈러",
        coverUrl: "https://image.yes24.com/goods/74719531/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 3,
      },
      {
        id: "seed-yes-4",
        title: "데일 카네기 인간관계론",
        author: "데일 카네기",
        coverUrl: "https://image.yes24.com/goods/15855097/XL",
        link: "https://www.yes24.com/",
        source: "seed",
        language: "ko",
        rank: 4,
      },
    ],
    englishBestsellers: [
      {
        id: "seed-en-1",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
        link: "https://openlibrary.org/works/OL16421130W",
        source: "seed",
        language: "en",
        rank: 1,
        publisher: "Farrar, Straus and Giroux",
      },
      {
        id: "seed-en-2",
        title: "Atomic Habits",
        author: "James Clear",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        link: "https://openlibrary.org/works/OL17930344W",
        source: "seed",
        language: "en",
        rank: 2,
        publisher: "Avery",
      },
      {
        id: "seed-en-3",
        title: "Nudge",
        author: "Richard H. Thaler, Cass R. Sunstein",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780143115267-L.jpg",
        link: "https://openlibrary.org/works/OL16492416W",
        source: "seed",
        language: "en",
        rank: 3,
        publisher: "Penguin",
      },
      {
        id: "seed-en-4",
        title: "The Black Swan",
        author: "Nassim Nicholas Taleb",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780812973815-L.jpg",
        link: "https://openlibrary.org/works/OL8463436W",
        source: "seed",
        language: "en",
        rank: 4,
        publisher: "Random House",
      },
      {
        id: "seed-en-5",
        title: "Capital in the Twenty-First Century",
        author: "Thomas Piketty",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780674430006-L.jpg",
        link: "https://openlibrary.org/works/OL17009656W",
        source: "seed",
        language: "en",
        rank: 5,
        publisher: "Harvard University Press",
      },
      {
        id: "seed-en-6",
        title: "Good to Great",
        author: "Jim Collins",
        coverUrl: "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg",
        link: "https://openlibrary.org/works/OL394260W",
        source: "seed",
        language: "en",
        rank: 6,
        publisher: "HarperBusiness",
      },
    ],
  },
};
